# SPDX-License-Identifier: Apache-2.0
"""A quarter's epic cards and stage grid, generated from the planning model.

An epic has two faces, kept apart on purpose. Its folder, under the `epicsDir` binding, is
written by hand and lives across quarters: framing, scope decisions and discovery. Its card,
under the `cardsDir` binding, is a view generated for one quarter: the rung movement, the
deliverables with their types, rungs, points, states and approvals, and budget against planned.
With the feature-request layer bound, it also shows the requests the epic takes on and the
products and platforms they support. The card links to the folder and never repeats it.

The capacity arithmetic is imported from capacity.py rather than recomputed, so a card's
budget is the figure the validation reports.

  build(q, bind, label) -> {path: text}
  write(files, check) -> the paths that were stale
"""
import io
import os
import re

from capacity import base_points, f, product_points
from planmodel import committed_ids, load_items, load_plan, load_register
import feature_requests as req_mod
from report import pts


def signed(x):
    return ('+' if x > 0 else '') + pts(x) if abs(x) > 0.005 else '0.0'


def md_table(head, rows):
    out = ['| ' + ' | '.join(head) + ' |', '|' + '---|' * len(head)]
    out += ['| ' + ' | '.join(str(c).replace('|', '\\|').replace('\n', ' ') for c in r) + ' |'
            for r in rows]
    return '\n'.join(out) + '\n'


def regenerate_command(bind, slug):
    return bind.command('cards') or (
        "the quarter-planning skill's `quarter.py --quarter %s --cards`" % slug)


def check_command(bind, slug):
    return bind.command('check') or ("the quarter-planning skill's `quarter.py --quarter %s`"
                                     % slug)


def frontmatter(title, label, position, bind, slug):
    return ('---\ntitle: "%s"\nsidebar_label: "%s"\nsidebar_position: %d\nstatus: Generated\n'
            '---\n\n<!-- Generated by the quarter-planning skill from the planning model. Do not '
            'edit: change the model or the epic\'s own folder, then regenerate with %s. -->\n\n'
            % (title.replace('"', "'"), label.replace('"', "'"), position,
               regenerate_command(bind, slug)))


def home_link(item, bind, cards_dir):
    """A sentence linking the card to the epic's own folder, or saying why it cannot."""
    home = str(item.get('home') or '').strip()
    if not home:
        return 'The epic has no home folder recorded. '
    epics = bind.optional('epicsDir')
    if not epics:
        return ('The epic records its home as `%s`, but no `epicsDir` is bound, so it cannot '
                'be linked. ' % home)
    target = os.path.normpath(os.path.join(epics, home))
    if os.path.isdir(target):
        page = next((os.path.join(target, n) for n in ('index.md', 'README.md')
                     if os.path.isfile(os.path.join(target, n))), None)
        if not page:
            return ('The epic\'s folder, `%s`, has no index.md or README.md to link to. '
                    % home)
        target = page
    elif not os.path.isfile(target):
        return 'The epic records its home as `%s`, which is not under the epics folder. ' % home
    link = os.path.relpath(target, cards_dir).replace(os.sep, '/')
    return ('The epic, with its framing, discovery and decisions, is [its own page](%s). '
            % link)


def position(item, n):
    m = re.search(r'(\d+)$', str(item.get('id') or ''))
    return 10 + (int(m.group(1)) if m else n + 1)


def card(item, n, q, bind, label, register, base, cards_dir, layer=None):
    ds = item.get('deliverables') or []
    planned = sum(product_points(d, base) for d in ds)
    derived = q.distribution.get(item['id'], 0.0)
    recorded = item.get('budget_points')
    flows = item.get('flows') or []
    reached = any(fl.get('rung_reached') for fl in flows)
    s = [frontmatter('%s card, %s' % (item['id'], label), '%s card' % item['id'],
                     position(item, n), bind, q.slug),
         '# %s card, %s\n\n' % (item['id'], label),
         '%s. ' % str(item.get('title') or 'Untitled').rstrip('.'),
         home_link(item, bind, cards_dir),
         'This card is the quarter\'s view of it, generated from the planning model.\n\n']
    s.append(md_table(['Field', 'Value'], [
        ['Quarter', item.get('quarter') or label],
        ['Capability area', item.get('lane') or 'None recorded'],
        ['Approval', item.get('approval') or 'draft'],
        ['Threads', ', '.join(item.get('threads') or []) or 'None recorded'],
        ['Criteria advanced', ', '.join(item.get('advances_criterion_ids') or [])
         or 'None recorded'],
    ]))
    s.append('\n## Movement\n\n')
    if flows:
        head = ['Flow', 'What it does', 'From', 'To'] + (['Reached'] if reached else [])
        s.append(md_table(head, [
            [fl.get('flow') or '', fl.get('description') or '', fl.get('rung_from') or '',
             fl.get('rung_to') or ''] + ([fl.get('rung_reached') or ''] if reached else [])
            for fl in flows]))
    else:
        s.append('No flows are recorded, so the movement is unstated.\n')
    s.append('\n## Deliverables\n\n')
    if ds:
        rows = []
        for d in ds:
            t = register.get((d.get('deliverable_id') or '').strip(), {})
            rows.append(['%s %s' % (d.get('id') or '', d.get('name') or ''),
                         d.get('deliverable_id') or '', (t.get('rung') or '').strip(),
                         pts(product_points(d, base)), d.get('state') or '',
                         d.get('approval') or 'draft'])
        s.append(md_table(['Deliverable', 'Type', 'Evidences', 'Points', 'State', 'Approval'],
                          rows))
    else:
        s.append('No deliverables are named yet.\n')
    if layer:
        s.append(requests_part(item, *layer))
    s.append('\n## Capacity\n\n')
    s.append(md_table(['Budget', 'Planned', 'Under or over'],
                      [[pts(derived), pts(planned), signed(derived - planned)]]))
    s.append('\n')
    gap = derived - planned
    if not derived:
        s.append('No budget has been given to this epic, so its deliverables are deferred.\n')
    elif gap < -bind.tolerance:
        s.append('Planned is over budget by %s points. Time and cost are fixed, so which '
                 'deliverables to defer is a scope decision for the owner.\n' % pts(-gap))
    else:
        s.append('Planned is within budget.\n')
    if recorded is not None and abs(f(recorded) - derived) > bind.tolerance:
        s.append('\nThe model records a budget of %s, which no longer follows from the '
                 'resourcing. The quarter\'s validation, %s, shows why.\n'
                 % (pts(f(recorded)), check_command(bind, q.slug)))
    return ''.join(s), derived, planned


def requests_part(item, reqs, products, story_map):
    """The feature requests the epic takes on, and the products and platforms they support."""
    on = req_mod.epic_requests(item, reqs)
    s = ['\n## Feature requests\n\n']
    if not on:
        s.append('This epic takes on no feature request.\n')
        return ''.join(s)
    rows = []
    for rid in on:
        r = reqs[rid]
        score = req_mod.wsjf(r)
        title = (r.get('title') or '').strip()
        rows.append(['%s %s' % (rid, title) if title else rid,
                     (r.get('product') or '').strip(),
                     (r.get('requested_by') or '').strip(), (r.get('status') or '').strip(),
                     pts(score) if score is not None else '',
                     ', '.join(story_map.get(rid, [])) or 'None yet'])
    s.append(md_table(['Request', 'Product', 'Requested by', 'Status', 'WSJF', 'Stories'], rows))
    s.append('\n## Products and platforms supported\n\n')
    sup = req_mod.supported(on, reqs, products)
    if sup:
        s.append(md_table(['Product', 'Platform', 'Team', 'Requests'], [
            ['%s %s' % (pid, p.get('name')) if p.get('name') else pid,
             (p.get('platform') or '').strip(), req_mod.team_of(p), ', '.join(rs)]
            for pid, p, rs in sup]))
    else:
        s.append('The requests name no product.\n')
    return ''.join(s)


def grid(epics, summary, q, bind, label):
    s = [frontmatter('%s stage grid' % label, 'Stage grid and cards', 1, bind, q.slug),
         '# %s stage grid\n\n' % label,
         'Where each flow in scope starts on the definition ladder, and the rung its epic is '
         'committed to reach. Generated from the planning model.\n\n']
    reached = any(fl.get('rung_reached') for e in epics for fl in e.get('flows') or [])
    rows = [[e.get('lane') or '', fl.get('flow') or '', fl.get('rung_from') or '',
             fl.get('rung_to') or ''] + ([fl.get('rung_reached') or ''] if reached else [])
            + ['[%s](./%s.md)' % (e['id'], e['id'])]
            for e in epics for fl in e.get('flows') or []]
    if rows:
        s.append(md_table(['Capability area', 'Flow', 'Start', 'Committed']
                          + (['Reached'] if reached else []) + ['Card'], rows))
    else:
        s.append('No epic in the quarter records any flows yet.\n')
    s.append('\n## Epics\n\n')
    s.append(md_table(['Epic', 'Title', 'Budget', 'Planned', 'Under or over', 'Approval'],
                      [['[%s](./%s.md)' % (e['id'], e['id']), e.get('title') or '', pts(b),
                        pts(p), signed(b - p), e.get('approval') or 'draft']
                       for e, b, p in summary]))
    return ''.join(s)


def build(q, bind, label):
    """Every file the cards folder should hold for this quarter, as {path: text}."""
    items, _ = load_items(bind, label)
    by_id = {w['id']: w for w in items}
    plan = load_plan(bind, label)
    ids = committed_ids(plan, items, label, budgeted=q.budget(by_id))
    epics = [by_id[i] for i in ids if i in by_id]
    register = load_register(bind)
    base = base_points(bind)
    cards_dir = bind.resolve('cardsDir')
    reqs = req_mod.load_requests(bind)
    layer = ((reqs, req_mod.load_products(bind), req_mod.stories(bind))
             if reqs is not None else None)
    out, summary = {}, []
    for n, e in enumerate(epics):
        text, b, p = card(e, n, q, bind, label, register, base, cards_dir, layer)
        out[os.path.join(cards_dir, '%s.md' % e['id'])] = text
        summary.append((e, b, p))
    out[os.path.join(cards_dir, 'README.md')] = grid(epics, summary, q, bind, label)
    return out


def write(files, check=False):
    """Write what has changed, or with check, only report it. Returns the stale paths."""
    stale = []
    for path, text in files.items():
        old = io.open(path, encoding='utf-8').read() if os.path.isfile(path) else None
        if old != text:
            stale.append(path)
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with io.open(path, 'w', encoding='utf-8', newline='\n') as fh:
                    fh.write(text)
    return stale
